[project]
name = "cfms-on-websocket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.3",
    "filetype>=1.2.0",
    "jsonschema>=4.25.1",
    "pycryptodome>=3.23.0",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.44",
    "tomlkit>=0.13.3",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.21.0",
]
