debug = false

[server]
name = "CFMS WebSocket Server"
host = "localhost"
port = 5104
dualstack_ipv6 = true
secret_key = ""
ssl_keyfile = "./content/ssl/key.pem"
ssl_certfile = "./content/ssl/cert.pem"

file_chunk_size = 2097152 # 2MB
# 过高的分块大小可能因客户端的配置而导致传输失败

[document]
allow_name_duplicate = false
# 是否允许同目录下的文档名称重复
# 如果在允许重复后又设置为禁止重复，原有的重复文档将被保留
# 但新上传的文档将会被拒绝

[security]
passwd_min_length = 8
passwd_max_length = 32
enable_passwd_force_expiration = true
# 启用密码强制过期策略
require_passwd_enforcement_changes = true
# 启用不合规密码强制更改策略
# 使用不合规的密码的用户在登录时将被强制要求修改密码
passwd_expire_after_days = 365
passwd_must_contain = []

[database]
type = "sqlite"

# 如果使用 SQLite 数据库，指定数据库文件名
file = "app.db"

# 如果使用 MySQL 数据库，指定连接信息
host = "localhost"
port = 3306
username = ""
password = ""
# 如果使用 MySQL 数据库，指定数据库名称
db_name = "app_db"
# 如果使用 MySQL 数据库，指定字符集
charset = "utf8mb4"
options = "" # Not implemented yet